m4_divert(-1)

# --------------------------------------------------------------- #
m4_define(`DM_BEGIN',    `m4_divert(1)<!--
This is autogenerated from template README.in
DO NOT MODIFY THIS FILE
-->')
# --------------------------------------------------------------- #

# --------------------------------------------------------------- #
# Channel 3 is the title. Channel 6 is after the title.
  m4_define(`DM_TITLE',    `m4_divert(3)`'`#' $1`'m4_divert(6)
`'m4_dnl`'')`'m4_divert(-1)
# --------------------------------------------------------------- #

# --------------------------------------------------------------- #
# Channel 4 is the subtitle. Channel 7 is after
m4_define(`DM_SUBTITLE', `m4_divert(4)`'_`'$1`'_'`'m4_divert(7)`')`'m4_divert(-1)
# --------------------------------------------------------------- #

# --------------------------------------------------------------- #
# Channel 5 are the section names
m4_define(`DM_SECTION',  `m4_divert(5)  - [$1](`#'`'m4_translit(`$1', `A-Z ', `a-z-'))
`'m4_divert(2)
`##' $1`'')
m4_define(`DM__SECTION', `DM_SECTION($1)')
# --------------------------------------------------------------- #

# --------------------------------------------------------------- #
# TODO: make them links in the table of contents?!
m4_define(`DM_SUBSECTION',  `m4_divert(2)m4_dnl
`###' $1')
# --------------------------------------------------------------- #

# --------------------------------------------------------------- #
m4_define(`DM_END', `m4_divert(0)`'m4_dnl
m4_undivert(3)`'m4_dnl
m4_undivert(6)`'m4_dnl
m4_undivert(4)`'m4_dnl

*****
m4_undivert(5)
*****
m4_undivert(2)
m4_m4exit(0)`'')
# --------------------------------------------------------------- #

# --------------------------------------------------------------- #
# yay, first recursive macro
m4_define(`DM_SMALL2', DM_SMALL1(`<sup>$1</sup>'))
# --------------------------------------------------------------- #

# --------------------------------------------------------------- #
m4_define(`DM_SMALL1', `<sup>$1</sup>')
# --------------------------------------------------------------- #

# --------------------------------------------------------------- #
m4_define(`DM_CODE', `DM_FIXED_WIDTH($1)')
m4_define(`DM_CODE_BLOCK', `DM_PRE($1)')
m4_define(`DM_FIXED_WIDTH', `DM_BACKTICK`'$1`'DM_BACKTICK')
m4_define(`DM_PRE', `DM_BACKTICK`'DM_BACKTICK`'DM_BACKTICK
$1`'DM_BACKTICK`'DM_BACKTICK`'DM_BACKTICK')

m4_define(`DM_BACKTICK', m4_changequote([,])[m4_changequote([,])`m4_changequote(`,')]m4_changequote(`,'))
m4_define(`DM_SINGLEQUOTE', m4_changequote([,])[m4_changequote([,])'m4_changequote(`,')]m4_changequote(`,'))
# --------------------------------------------------------------- #

# --------------------------------------------------------------- #
m4_define(`DM_ITALIC', `_$1_')
m4_define(`DM_BOLD', `__$1__')
# --------------------------------------------------------------- #

# --------------------------------------------------------------- #
m4_define(`DM_INCLUDE', `m4_include($1)m4_dnl')
# --------------------------------------------------------------- #


# --------------------------------------------------------------- #
m4_define(`DM_BEGIN_COLLAPSIBLE', `<details>
  <summary>Click here to expand</summary>
')
m4_define(`DM_END_COLLAPSIBLE', `
</details>m4_dnl')
# --------------------------------------------------------------- #



# --------------------------------------------------------------- #

# going to end ride for newlines 4 free
m4_divert(0)m4_dnl
m4_divert(-1)m4_dnl
